Vagrant.configure("2") do |config|
    config.vm.synced_folder "/tmp/vagrant_synced/", "/tmp/vagrant_synced", create: true

    config.vm.define "postgres" do |postgres|
         postgres.vm.box = "precise32"
         postgres.vm.provision "shell", path: "provision_postgres.sh"
         postgres.vm.hostname = "fdmpg"
         postgres.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "512"]
              vb.customize ["modifyvm", :id, "--cpus", "1"]
         end
         postgres.vm.network :private_network, ip: "192.168.255.4"
    end

    # tomcat's VM
    # configuration files are copied via script "provision_tomcat.sh"
    config.vm.define "tomcatManu" do |tomcat|
        tomcat.vm.box = "tomcatManu"
        tomcat.vm.provision :shell, path: "provision_tomcat.sh"
        tomcat.vm.provision "restart_tomcat", type: "shell", inline: 'service tomcat restart'
        tomcat.vm.provision "copy_war", type: "shell", path: "copy_war.sh"
        tomcat.vm.network :private_network, ip: '192.168.33.11'
        tomcat.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
    end

end