Vagrant.configure("2") do |config|

     config.vm.synced_folder "/tmp/vagrant_synced/", "/tmp/vagrant_synced", create: true

#    config.vm.define "fdmcm" do |fdmcm|
#        fdmcm.vm.box = "saucy64"
#        fdmcm.vm.provision "shell", path: "provision_cm.sh"
#        fdmcm.vm.hostname = "fdmcm"
#        fdmcm.vm.provider :virtualbox do |vb|
#            vb.customize ["modifyvm", :id, "--memory", "256"]
#            vb.customize ["modifyvm", :id, "--cpus", "1"]
#        end
#        fdmcm.vm.network :private_network, ip: "192.168.255.3"
#    end

    config.vm.define "fdmpg" do |fdmpg|
         fdmpg.vm.box = "precise32"
         fdmpg.vm.provision "shell", path: "provision_pg.sh"
         fdmpg.vm.hostname = "fdmpg"
         fdmpg.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "512"]
              vb.customize ["modifyvm", :id, "--cpus", "1"]
         end
         fdmpg.vm.network :private_network, ip: "192.168.255.4"
    end

    # tomcat's VM
    # tomcat is installed via script "tomcat.sh"
    config.vm.define "tomcat" do |tomcat|
        tomcat.vm.box = "precise32"
        tomcat.vm.provision :shell, path: "tomcat.sh"
        tomcat.vm.network :private_network, ip: '192.168.33.10'
        tomcat.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

#    config.vm.define "fdmmq" do |fdmmq|
#          fdmmq.vm.box = "centos59"
#          fdmmq.vm.provision "shell", path: "provision_mq.sh"
#          fdmmq.vm.hostname = "fdmmq"
#          fdmmq.vm.provider :virtualbox do |vb|
#               vb.customize ["modifyvm", :id, "--memory", "512"]
#               vb.customize ["modifyvm", :id, "--cpus", "1"]
#          end
#          fdmmq.vm.network :private_network, ip: "192.168.255.5"
#     end
end